### ISSUE TITLE
Resolve CORB (not CORS) errors with most health checks

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#13]
Despite enabling CORS in our health-checks servers, we are still getting CORB errors for requests, embed, and the library website. To see the errors, run either of the builds described in the readme. Jack and I did some poking around this today and I hope we can get a third and forth set of eyes on this, since we're sort of at an impasse.

## Context
We need to send GET requests for health checks to a handful of different servers, which live on a domain other than gh-pages, and then parse and render the returned plantext or json. Because they are on different domains, we need to enable CORS to include them in our javascript application. Unfortunately, for some reason, the browser has decided that despite the `Access-Control-Allow-Origin` policy and header being set to `*`, it will still not allow us to "read" it ("Cross-Origin Read Blocking").

https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md
https://youtu.be/dBuykrdhK-A?t=22m

The endpoint addresses are set here in [config.js](https://github.com/sul-dlss/searchworks-status/blob/master/src/config.js) and the requests are dispatched using [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) from [these lines](https://github.com/sul-dlss/searchworks-status/blob/master/src/Dashboard.js#L24-L89) in Dashboard.js. The request handling and parsing is done in [endpointParsers.js](https://github.com/sul-dlss/searchworks-status/blob/master/src/endpointParsers.js). Note that both fetch and the endpoint parsers return a promise. When the promise is resolved, the react component state is updated and re-rendered.

### Relevant Facts
- Requests-stage, embed, and library website all produce CORB errors
- Firefox and Safari also produce CORB errors for these requests
- Library hours does not produce any errors (though it is a bitstream, we are able to parse it)
- Purl does not produce any errors
- Calls to stacks CORS endpoints such as any IIIF manifest or info.json do not produce these errors

### What We Have Tried
1. Adding a static build version
At first we thought the dev server may have been responsible for causing some of these problems, but after creating the static build and deploying to gh-pages, the problem persists.
1. Using a request library instead of `fetch`
We tried including `axios` and making our requests that way, thinking perhaps there was a problem with the browser's `fetch` implementation. This didn't produce a different result.
1. Changing headers to `no-cors`, which causes all requests to "complete", but give opaque responses with no body
1. Changing headers to `cors`, which allows library hours through but gives CORB errors for all others
1. Setting `'X-Content-Type-Options': 'nosniff'` in fetch requests, which causes preflight response check failures on all checks

**Comment by aeschylus** [comment]
https://github.com/sul-dlss/searchworks-status/issues/22

Hosting under our own domain would remove the CORB errors. However, so far it has seemed that after a few days, after enabling CORS, the CORB errors also go away. I don't know why this would be.

**Comment by jkeck** [comment]
Should we claim this as resolve now?

**Comment by camillevilla** [comment]
We are deploying to GitHub pages and CORBS issues are now resolved in production. 
https://sul-dlss.github.io/searchworks-status/

**Comment by jkeck** [comment]
🕺
