### ISSUE TITLE
SW live-lookup from Bodoni

### ISSUE THREAD

**Issue by shelleydoljack** [sul-dlss/searchworks-status#16]
We want to check that the live-lookup works. There is a script on Bodoni called vufind.pl that returns item information data for SearchWorks. More info about it is at https://consul.stanford.edu/display/NGDE/Item+Status . If calling this script doesn't return data then something is wrong. If the something that is wrong is Symphony is down, then Library Systems will have been alerted through other means.

**Comment by aeschylus** [comment]
I notice we have some kind of suggestively-named health check through requests. Is this sufficient?
See: https://requests.stanford.edu/status/all.json
```
searchworks_api: {
message: "HTTP check successful",
success: true,
time: 0.11504142731428146
},
symphony_api: {
message: "Ping check to sulohsprod1.stanford.edu:80 successful",
success: true,
time: 0.04032905399799347
},
hours_api: {
message: "HTTP check successful",
success: true,
time: 0.15428004413843155
},
sul_illiad: {
message: "HTTP check successful",
success: true,
time: 0.49206991493701935
},
symphony_web_services: {
message: "Ping check to libwebprod1.stanford.edu:443 successful",
success: true,
time: 0.06195319443941116
}
```

**Comment by jkeck** [comment]
See sul-dlss/SearchWorks#1930 for potentially relevant SW OkComputer check.
