### ISSUE TITLE
UX and context of status page

### ISSUE THREAD

**Issue by jvine** [sul-dlss/searchworks-status#17]
1. - [x] Edit service names and status text to match our users' vocabulary and conform to SUL style guide. #60
2. - [x] Write help / descriptive text. #59 
3. Help / descriptive text should be editable with minimal overhead in response to user feedback & questions. (The library website may not be the best place for this for lots of reasons; but text embedded in applications tends to be inert.)
4. - [x] Link to some kind of feedback/contact information from the status page. #61
5. - [x] Add minimal branding & navigation context. #58 
6. - [x] Create a "friendly" direct-access URL.
7. Determine where the page will be linked from in: (sul-dlss/SearchWorks#2022)
   - SearchWorks
   - Libweb
   - Bento
   - elsewhere?

... is this everything?

**Comment by cmh2166** [comment]
Yes. Part of this needs to be answered in this work cycle to get the technical work done, part of this will be taken back up in the Searchworks App work cycle for integration with Searchworks etc. & branding / marketing questions.

**Comment by aeschylus** [comment]
I think number 3 above is handled by the current project setup. Any top-level content description can be placed in the [config file](https://github.com/sul-dlss/searchworks-status/blob/master/src/config.js). Please have a look if you get a chance and let me know if I can make it easier.

I made it a js file versus a json file so we can use comments for more context, if that would be helpful.

**Comment by camillevilla** [comment]
Remaining work has been captured in the project board epics.

**Comment by aeschylus** [comment]
I see this is marked as non-critical on the project board, but as I'm catching up I'm wondering if this isn't already handled by the methods outlined above. I know it's not easy for a non-technical person to test the total appearance of their changes, but the linter + tests should be able to catch any breaking changes. So a non-dev should be able to edit any *value* in the config and it would update the text for that key on the dashboard.
