### ISSUE TITLE
Create new Twitter feed to be leveraged by SW status

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/searchworks-status#2]
Will note planned outages & noted issues, i.e. Issue has been reported ; Issue has been resolved.

- Clearinghouse or multiple groups put it here.
- Embed Twitter feed in website
- Will also need to push updates to the main library status account (perhaps via @ mention).
- have wording on the application explain the scope of what twitter captures
- have light-weight process for who updates this when

**Comment by cmh2166** [comment]
Can't recall, but @aeschylus - were you working on this? want to assign yourself + move to in progress/

**Comment by mejackreed** [comment]
`searchworks-status@lists.stanford.edu` requested for management of this account.

**Comment by mejackreed** [comment]
User https://twitter.com/searchworks created. Pending list creation will send login details/credentials to team via private communication channels.
