### ISSUE TITLE
Passing libweb status checks are reported as failures

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/searchworks-status#236]
See, for example: 
![Screen Shot 2020-09-23 at 1 19 34 PM](https://user-images.githubusercontent.com/73732/94065071-769f4c00-fd9f-11ea-8513-325655e9e8a2.png)

The healthcheck endpoint is returning: 

```
Successfully bootrapped the drupal database.<br />
Master database responding as expected.<br />
Successfully created temporary file in the files directory.<br />
Successfully deleted newly created file in files directory.<br />
Successfully set redis value.<br />
Successfully cleared redis value.<br />
All Health Checks Successfull! 200
```

However, it looks like this in the browser: 
![Screen Shot 2020-09-23 at 1 21 25 PM](https://user-images.githubusercontent.com/73732/94065299-d269d500-fd9f-11ea-9f8e-d8ad52319ea3.png)

**Comment by mejackreed** [comment]
@anarchivist Is there an escalation path for SulWeb team? There seems to be an issue with that healthcheck no longer supporting CORS.

https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Flibrary.stanford.edu%2Fhealthcheck.php&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote

This is causing the issue.

**Comment by anarchivist** [comment]
Thanks @mejackreed; it probably has to do with a recent server migration. I'll raise it to Ops.
