### ISSUE TITLE
Write wording for SW status about what happens when something is not “No Issues”

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/searchworks-status#3]
*  Include Contact us (how, where, who) => link to feedback form
* What do statuses mean
* behind the scenes reporting scenarios
* If we’re down, we’re down and alerting occurs.

**Comment by aeschylus** [comment]
As far as wording or "strings" are concerned, I've broken these out into [`config.js`](https://github.com/sul-dlss/searchworks-status/blob/master/src/config.js).

**Comment by cmh2166** [comment]
To be revisited in group meeting, per planning discussion on 8/28.

**Comment by camillevilla** [comment]
Closed by #69
