### ISSUE TITLE
Establish a convention (PR template, README section) to ensure package-lock changes are always included if necessary

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#32]

**Comment by mejackreed** [comment]
I wonder if we are running into issues with differences between people using npm 5 and npm 6?

**Comment by jkeck** [comment]
Ah, I think you may be right.  After upgrading my local npm I'm certainly getting a lot less changes.

However; I'm not getting several `resolved` values changing from `http` to `https` (which is probably good).  This is under npm version 6.4.1, so, maybe this is something that has been updated recently.

**Comment by mejackreed** [comment]
Hopefully #67 helps here?
