### ISSUE TITLE
Generate or select New Relic Pro graphs to embed for the relevant questions:

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/searchworks-status#4]
* Average solr response time (Web transactions view?)
* Searchworks page load time
* Response time from Ebsco

**Comment by camillevilla** [comment]
We'll want to grab embed codes from this subset of graphs:
https://insights.newrelic.com/accounts/1477374/dashboards/690511

**Comment by aeschylus** [comment]
@camillevilla has set up what I think are the desired graphs here: https://insights.newrelic.com/accounts/1477374/dashboards/690511

The insights panel doesn't allow you to embed the graphs chosen there (as far as I can tell), and reconstructing them in the main APM tab in New Relic is a bit fidgety, so here are the reconstructions:

``` javascript
swResponseTime: {
    title: 'Searchworks Response Time',
    tag: '<iframe src="https://rpm.newrelic.com/public/charts/9kReJWHRXyt" width="500" height="300" scrolling="no" frameborder="no"></iframe>',
    position: 1
  },
  solr: {
    title: 'Solr Response Time',
    tag: '<iframe src="https://rpm.newrelic.com/public/charts/tAPstSMLa7" width="500" height="300" scrolling="no" frameborder="no"></iframe>',
    position: 1
  },
  ebsco: {
    title: 'Ebsco Response Time',
    tag: '<iframe src="https://rpm.newrelic.com/public/charts/gaCwQOqamfZ" width="500" height="300" scrolling="no" frameborder="no"></iframe>',
    position: 2
  }
```

The urls for these are stored in [`config.js`](https://github.com/sul-dlss/searchworks-status/blob/master/src/config.js)

**Comment by cmh2166** [comment]
@jvine can give more insight, but for the 2 remaining questions on this ticket:

1. `SearchWorks Response Time` seems fine to me. `Solr (Index) Response Time` might help (add something to let them know it is about the index?). `Ebsco Response Time` could perhaps use a small explanation (i.e. `Ebsco Articles Search Response Time` or the like).

2. What are the time horizons captured now? A month seems good to me, but I'm just putting a random number out there.

**Comment by jvine** [comment]
I'm working on wording for the options in config.js - should I append them to this issue, or create a new one?

**Comment by cmh2166** [comment]
let's create a new one. will discuss further tomorrow.
