### ISSUE TITLE
Refactor fetch request logic to avoid sending multiple requests to searchworks okcomputer endpoint

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#51]
@jkeck pointed out that we're calling the searchworks OKComputer endpoint multiple times. We should try to minimise these requests so the searchworks servers don't get swamped when people are checking status (probably when the server is already under load for some reason).

**Comment by jkeck** [comment]
This came up in planning today.  It would be nice to wrap this up.  Maybe we can huddle on this at some point to talk about if #66 is the right approach and how we can push this forward.
