### ISSUE TITLE
Add minimal SUL theming

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#58]

**Comment by jvine** [comment]
- [ ] Add Source Sans Pro font
`<link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700">`  
`font-family: 'Source Sans Pro', sans-serif;`
- [ ] Add SUL logo - source https://consul.stanford.edu/display/Logos/Home
`height: 35px;`
- [ ] Apply standard breakpoints
     ```
     @media (max-width: 768px) {  ... {padding: 0 15px;}}
     @media (min-width: 768px) {  ... {width: 750px;}}
     @media (min-width: 980px) {  ... {width: 970px;}}
     @media (min-width: 1200px) {  ... {width: 1170px;}}
     ```
- [ ] Add viewport meta tag  `<meta name="viewport" content="width=device-width,initial-scale=1.0">`
- [ ] Apply heading styles
     ```
     h1 {
    font-size: 2.441em;
    font-weight: 300;
    color: #3f3c30;
     }
     h2 {
    font-size: 1.953em;
    font-weight: 300;
    color: #544948;
     }
     h3 {
    font-size: 1.563em;
    font-weight: normal;
    color: #544948;
     }
     h3.service-name {
    font-size: 1.25em;
     }
    ```
- [ ] Revise page title to `<title>SearchWorks status : Stanford Libraries</title>`
- [ ] Revise heading structure for accessibility

* h1.  SearchWorks status
   "Global status" text is just a div, styled with same font size as h1
  * h2. Current service status
    * h3. Services names 
  * h2. Updates
  * h2. Performance metrics
    * h3. Graph titles

**Comment by jvine** [comment]
<img width="1440" alt="sw-status-full-page" src="https://user-images.githubusercontent.com/6945691/45986251-3a557b80-c01f-11e8-83fb-3bbc9f538449.png">
