### ISSUE TITLE
Add descriptive text where needed

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#59]
Perhaps give a short description of what the services are, or some contextual explanatory text near the top of the page to give more context to the meaning of the global service status.

**Comment by jvine** [comment]
### Replace text (for terminology and case)
- [ ] `Searchworks Status` -> `SearchWorks status`
- [ ] `Dashboard` -> `Current status`
- [ ] `Graphs` -> `Performance`
- [ ] `Current Service Status` -> `Current service status`

### Add text
- [ ] Below Updates heading, add `<p>The SearchWorks team will tweet updates about notable service interruptions.</p>`
- [ ] Below Performance metrics heading, add `<p>Sharp spikes in the graphs may have been experienced as momentary outages.</p>`
