### ISSUE TITLE
Nagios checks needed for anything for the SW status checks

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/searchworks-status#6]
If so, we can’t call it & need to find work-arounds. Question to be answer

**Comment by mejackreed** [comment]
Looked into something yesterday, and depending on Ops considerations, it looks like there is a way to automate nagios alerts to trigger status change for StatusPage.io components.

**Comment by mejackreed** [comment]
I'm not sure this ticket is actionable any further. @cmh2166 can you confirm?

**Comment by jkeck** [comment]
Closing this as I agree that this is not really actionable.  Will open new tix for anything that are needed.
