### ISSUE TITLE
Add a feedback form or contact method to this dashboard

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#61]

**Comment by jvine** [comment]
I propose a footer that provides links to the SearchWorks feedback form `https://searchworks.stanford.edu/feedback` and the library website feedback form `https://library.stanford.edu/ask/email/feedback`, in the hope that at least one of them will be available. 

<img width="1353" alt="screen shot 2018-09-24 at 4 09 23 pm" src="https://user-images.githubusercontent.com/6945691/45984281-2c9af880-c015-11e8-855d-be626880444e.png">

**Comment by camillevilla** [comment]
@jvine and @aeschylus to discuss 9/27

**Comment by jvine** [comment]
After discussing w @aeschylus and @ahafele - we're exploring the idea of using an embedded Google form for feedback.

I've created a form in the Access team drive. Here's the embed code:

```
<div id="feedback" class="section">
<iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfO_IAoIZI28vSxAErtIwquqpUm7EqJtIj3DP14xQFa2M4-Wg/viewform?embedded=true" width="100%" height="748" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>
```

This solves the issue that the existing SW and website feedback forms might not be available when systems are down. However, we can't quite figure out how to make notifications work in a useful way. It can be set to send an email notification with each submission - however, it seems to only send to the owner of the form - i.e. an individual. **Can figure out how to make the form notify a mailing list?**

<img width="1320" alt="screen shot 2018-09-27 at 4 41 23 pm" src="https://user-images.githubusercontent.com/6945691/46180237-366e6700-c274-11e8-8cb0-52f04a277ab4.png">
