### ISSUE TITLE
Figure out a way to reduce bundle further.

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/searchworks-status#62]
Moment.js and moment-timeline are really the big ones here. I wonder if there is a way we can do the timezone calculation w/out these?

**Comment by aeschylus** [comment]
We could use [preact](https://preactjs.com/) instead of react. I don't think we're using any react-only features. How small is small enough?

**Comment by mejackreed** [comment]
I don't think that is what is most of our bulk. 75% is moment stuff I believe.

**Comment by aeschylus** [comment]
Current bundle size is 94kb

<img width="775" alt="screen shot 2018-09-11 at 11 03 49 am" src="https://user-images.githubusercontent.com/145874/45378514-7cf46e00-b5b2-11e8-96aa-7289b20e1a45.png">

It would be nice to get rid of some of the moment.js stuff. We could tree-shake with webpack, or attempt to write a bunch of timezone management stuff, which may be worth it, but it's usually a pain in the butt. We only use a couple conversion methods, so we could try going in and copying the source implementation for those out of moment. Jessy, Camille, and I spent a little bit futzing with it using the browser's own APIs (which vary across browsers) and were able to quickly put it aside using a library.

**Comment by mejackreed** [comment]
yeah .. i guess 95kb gzipped isn't too bad. Maybe we are good enough for now.
