### ISSUE TITLE
For Global Status Indicator, revise outage categories

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#64]
If the website is down **or** both SOLR and Articles are down, that's a "fatal" error category (red circle + alternative "fatal" text).

If **either** SOLR or Articles is down (but not both), then give the "critical" status (red circle, with "critical" text that is distinct from "fatal").

Any other single outage should give a yellow "issues" status.

Currently the text is the same for all "critical" statuses, and the global status text is the same as that in the table. We have the ability to display a special `global_message` for the top-level status indicator through the config, but also need to check for the new, proposed, "fatal" category and have a specific message for that.

**Comment by jkeck** [comment]
Quick clarifying question:

> Any other single outage should give a yellow "issues" status.

Does this mean that if any of the the website, SOLR, or Articles checks individually is returning a `yellow "issues" status` that would also bubble up to the global status to be a `yellow "issues" status`?

**Comment by jvine** [comment]
Any individual red outage for the checks not mentioned above (e.g. library hours) should give a yellow issues global status.
