### ISSUE TITLE
SW Health Checks list needs to be prioritized...

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/searchworks-status#7]
... based on what we need and what already exists for the end user monitoring application

**Comment by aeschylus** [comment]
From what I am aware of, these are the functioning endpoints.



``` js
 libraryHours: {
    displayName: 'Library Hours',
    endpointUrl: 'https://library-hours.stanford.edu/is_it_working' // returns a bitstring that evaluates to an annoying-to-parse text blob.
  },
  requests: {
    displayName: 'SUL Requests',
    endpointUrl: 'https://requests.stanford.edu/status/all.json' // needs CORS enabled
  },
  bitly: {
    displayName: 'Shortlink Redirects',
    endpointUrl: 'http://status.bitly.com/?format=json'
  },
  embed: {
    displayName: 'SUL Embed',
    endpointUrl: 'http://embed.stanford.edu/status/all.json' // needs CORS enabled
  }
```

**Comment by aeschylus** [comment]
Example of how to enable CORS for only the specified health-check route:

https://github.com/sul-dlss/puppet/blob/production/hieradata/node/sul-purl-prod-a.stanford.edu.eyaml#L142-L144

**Comment by shelleydoljack** [comment]
I think we also need to show that the indexing of MARC and Course data is happening. But I guess that depends on are triggering mechanisms for it, upon which we still need to decide. Currently, we rely on a log email from the indexing scripts containing the keyword “fatal error” to let us know that indexing has failed. It would be better to have this on the dashboard and an additional alert to the appropriate on call team.

**Comment by cmh2166** [comment]
@shelleydoljack lets leave that off of searchworks-status until we can figure out 
1. what + where the data control reports will occur (that covers a part of the internal user monitoring needs we have) and 
2. who actually needs to see that & how (monitoring of the indexing process should go to libsys, ops, etc., but maybe not be detailed on this end user application except in the most general of ways). that feels like a monitoring discussion for productionizing traject.

**Comment by cmh2166** [comment]
To be proposed at planning for these last sprints: if we're unclear still about any endpoint, leave the ticket open, document what we found out (or didn't), and leave it behind for this work cycle.

**Comment by shelleydoljack** [comment]
The Symphony api and Symphony web services api are not the same as the live lookup but different services on different servers. Maybe the SearchWorks api calls vufind.pl on Bodoni?

**Comment by camillevilla** [comment]
So these are configured here and rely on URLs in the `settings.yml`:
https://github.com/sul-dlss/sul-requests/blob/master/config/initializers/okcomputer.rb

The `hours_api` and `searchworks_api` are just hitting the OKcomputer endpoints that we're using. I'd propose we keep things separate so that one outage doesn't affect our ability to check the status of other services.

**Comment by aeschylus** [comment]
Agree in general @camillevilla. I was just wondering if we were getting some checks for free, and if we should include them in that case. I don't think there's a need to reduce the size of the health check response.

**Comment by cmh2166** [comment]
Closing this. Please use specific endpoint tickets to track work.
