### ISSUE TITLE
Address accessibility problems.

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#80]
- [ ] Icon fonts/ alt-text for screen-readers
- [x] Heading Structure

**Comment by saseestone** [comment]
@camillevilla are the Icon fonts/alt text still outstanding after your work last week on accessibility?  Just trying to figure out the status on this ticket...

**Comment by camillevilla** [comment]
@saseestone I haven't considered this explicitly. But I assume that any issues with the icons would have been addressed by @jvine's screenreader audit in #75?

**Comment by jvine** [comment]
Not icon fonts after all and the characters read as expected by a screen reader.
