### ISSUE TITLE
Graph disappears when user clicks on data point column

### ISSUE THREAD

**Issue by saseestone** [sul-dlss/searchworks-status#81]
If you hover your mouse over the graph portion immediately underneath the Data point column, it appears that the graph is clickable.  If you do click, the graph disappears.

**Comment by mejackreed** [comment]
Yep it trys to log you into new relic, which our users will not be able to do.

**Comment by mejackreed** [comment]
@saseestone @jvine I've been looking into this. There is a way to disable all mouse events on these embedded charts, but doing so would also disable the hover tooltip. Is that acceptable?

**Comment by jvine** [comment]
This tooltip?

<img width="269" alt="screen shot 2018-09-27 at 12 45 41 pm" src="https://user-images.githubusercontent.com/6945691/46170672-46298380-c253-11e8-8a8b-ba736650ec91.png">

because that seems pretty useful. 

I don't know if I'm an anomaly, but only the SW page load time chart disappears for me. The other two, I can click and nothing happens.

**Comment by mejackreed** [comment]
I think that may be an anomaly, they all exhibit the same behavior on "scrubbing" action.

I agree its pretty useful, but realize its a tradeoff. Any other click or drag action will cause a login prompt issue for a user and redirect.

**Comment by mejackreed** [comment]
And yeah.. that tooltip.

**Comment by jvine** [comment]
Hm. On mobile, touch triggers the tooltip, and doesn't make the graph disappear. Is there any way to make that behaviour consistent? I.e. touch/click triggers the tooltip? (and rainbows and puppies)

I am feeling pretty strongly about not losing the tooltip, but I honestly don't know how problematic the click/disappear behaviour will be and whether that outweighs everything else. 

I'm getting really mixed behaviour. 
Chrome & Firefox:  Only SW page load disappears on click. Range selection leads to login page.
Safari:  None of them disappear on click. Range selection leads to login page.

**Comment by mejackreed** [comment]
Unfortunately it seems like our hands are tied a bit here as we are injecting this via an iframe. We can do some things via css `pointer-events: none` but can't really inject custom JavaScript.

**Comment by saseestone** [comment]
I agree with Jennifer that the tooltip contains information that helps the user understand time on the graph, and (for me) showing it outweighs the less-than-optimal click/disappear behavior.

**Comment by aeschylus** [comment]
Looking at this with Jennifer yesterday we noticed that the click only causes a problem when clicking under the curve (in the highlighted area). Also, it seems if you try to click and drag the mouse to select/scrub the timeline, it will attempt to completely redirect you to New Relic, which of course fails for anyone who isn't logged in.

**Comment by mejackreed** [comment]
Decision to close
