### ISSUE TITLE
Create 3-button pill picker for performance graph time horizons

### ISSUE THREAD

**Issue by aeschylus** [sul-dlss/searchworks-status#89]
Talking with @jvine yesterday, we settled on the idea of adding a three-button pill picker above each graph to load separate graphs for three time horizons. After playing around in New Relic a bit with different horizons, we decided on views for:
- 6 hours
- 3 days
- 30 days

Where possible (possibly not meaningful for SOLR and Ebsco).

**Comment by camillevilla** [comment]
It seems like the apdex score overlay that was added recently interferes with a user's ability to hover over a point in the graph and see a time range. 

![apdex](https://user-images.githubusercontent.com/5402927/46311734-01199000-c578-11e8-9470-f5636b755bd8.gif)
