### ISSUE TITLE
Add OCLC services to health checks

### ISSUE THREAD

**Issue by camillevilla** [sul-dlss/searchworks-status#9]
Part of #7 

8/23: Sent an inquiry to OCLC re: public status APIs. If they don't have any, we'll have to parse these:
[WorldCat Search API](https://oclc.service-now.com/status?id=service&sys_id=3b1c847a4ff6e684a5832cee0210c759) (citations service)
[EZproxy (hosted)](https://oclc.service-now.com/status?id=service&sys_id=a135f987139f6e40250a36722244b098)

![single oclc service status page](https://user-images.githubusercontent.com/5402927/44545181-399c9300-a6c9-11e8-8de2-9bce2886177c.png)

OR grab them both from this dashboard page. We could cut down the number of HTTP requests but it would more tightly coupled to their CSS
https://oclc.service-now.com/status

![oclc_status_dashboard](https://user-images.githubusercontent.com/5402927/44545185-3b665680-a6c9-11e8-8ccf-abda6ef10964.png)

**Comment by cmh2166** [comment]
Any help I can offer with this wrt OCLC contacts?

**Comment by cmh2166** [comment]
- https://github.com/sul-dlss/searchworks-status/pull/39 closes citation work, proxy to health check.
- ezproxy left uncertain, opening new ticket.
